---
- name: Gather AWS S3 Bucket Information
  hosts: localhost
  gather_facts: false
  
  vars:
    aws_region: "{{ aws_region | default('us-east-1') }}"
    output_file: "{{ output_file | default('s3_buckets_info.json') }}"
  
  tasks:
    - name: Ensure required Python packages are installed
      pip:
        name:
          - boto3
          - botocore
        state: present
      become: true
      
    - name: Get list of all S3 buckets
      amazon.aws.aws_s3_bucket_info:
        region: "{{ aws_region }}"
      register: s3_buckets
      
    - name: Set up empty list for bucket details
      set_fact:
        bucket_details: []
        
    - name: Get creation information for each bucket
      block:
        - name: Get bucket tagging for creation info
          amazon.aws.s3_bucket_tagging_info:
            name: "{{ item.name }}"
            region: "{{ aws_region }}"
          register: bucket_tags
          loop: "{{ s3_buckets.buckets }}"
          ignore_errors: true
          
        - name: Get CloudTrail events for bucket creation
          shell: >
            aws cloudtrail lookup-events 
            --lookup-attributes AttributeKey=EventName,AttributeValue=CreateBucket 
            --region {{ aws_region }}
            | grep -B 5 -A 5 "{{ item.name }}"
          register: cloudtrail_results
          loop: "{{ s3_buckets.buckets }}"
          ignore_errors: true
          
        - name: Compile bucket information
          set_fact:
            bucket_details: "{{ bucket_details + [{ 
              'name': item.0.name, 
              'creation_date': item.0.creation_date,
              'creator_from_tags': item.1.tags.CreatedBy | default('Unknown') if (item.1.tags is defined and item.1.tags.CreatedBy is defined) else 'Unknown',
              'creator_from_cloudtrail': item.2.stdout if item.2.stdout != '' else 'Not found in CloudTrail history'
            }] }}"
          loop: "{{ s3_buckets.buckets | zip(bucket_tags.results, cloudtrail_results.results) | list }}"
          
    - name: Display bucket information
      debug:
        var: bucket_details
        
    - name: Save bucket information to file
      copy:
        content: "{{ bucket_details | to_nice_json }}"
        dest: "{{ output_file }}"
      
    - name: Generate HTML report
      template:
        src: s3_report_template.j2
        dest: s3_buckets_report.html
      
  post_tasks:
    - name: Show summary
      debug:
        msg: "Found {{ s3_buckets.buckets | length }} S3 buckets. Details saved to {{ output_file }} and s3_buckets_report.html"
